# -*- coding: utf-8 -*-
"""python task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1houqnUEur68tdTMAwd-FGJN5Nef6l3wS
"""

list = []
for i in range(2000, 3201):
    if i % 7 == 0 and i % 5 != 0:
        list.append(i)
print(list)



def factorial(n):
    value = 1
    for i in range(1, n+1):
        value = value * i
    return value
number = int(input("number: "))
print(factorial(number))

n=int(input("Enter the Number"))
new_dict = {}
for i in range(1,n+1):
	new_dict[i]=i*i
print(new_dict)

numbers = input("enter some values :")
numbers_list = numbers.split(',')
number_tuple = tuple(numbers_list)
print(number_tuple)
print(numbers_list)

def getString():
    input_string = input("Enter a string:")
    return input_string
def printString(user_string):
    print(user_string.upper())
    def test_function():
      test_function.getstring()
      test_function.printstring()
      print(test_function)

import math
C = 50
H = 30
D_values = input("Enter comma-separated values for D: ").split(',')
Q_values = []
for D in D_values:
    D = int(D)
    Q = math.sqrt((2 * C * D) / H)
    Q_values.append(round(Q))
print(*Q_values, sep=',')

X_Y = input("Enter two values (X,Y) separated by a comma: ").split(',')
X = int(X_Y[0])
Y = int(X_Y[1])
array = []
for i in range(X):
    row = []
    for j in range(Y):
        row.append(i * j)
    array.append(row)
print(array)

words = input("Enter comma-separated words: ").split(',')
words.sort()
print(words)

def to_uppercase(text):
    """Converts the input text to uppercase."""
    return text.upper()
text_input = input("Enter a string: ")
uppercase_output = to_uppercase(text_input)
print(uppercase_output)

x = input("enter the string:")
if x is (x.lower()):
    print(x.upper())
else:
    print(x.lower())

B_numbers = input("enter 4digit binary num seperated by comma:").split(',')
divided_5  = []
for binary in B_numbers:
 if int(binary, 2) % 5 == 0:
   divided_5.append(binary)
print(divided_5)

list = []
for i in range(1000,3000):
    if i % 2 == 0:
        list.append(i)
print(list)

letters = input("enter the letters:")
digits = input("enter the digits:")
for i in letters:
    if i.isalpha():
        print(i)
for j in digits:
    if j.isdigit():
        print(j)

string = input("enter the string values:")
if string.isupper():
  print(string.lower())

a = input("Enter a digit: ")
value_a = int(a)
value_aa = int(a * 2)
value_aaa = int(a * 3)
value_aaaa = int(a * 4)
final_output = value_a + value_aa + value_aaa + value_aaaa
print(final_output)

sentence = input("Type a sentence: ")
upper_case = lower_case = 0
for char in sentence:
    if 'A' <= char <= 'Z':
        upper_case += 1
    elif 'a' <= char <= 'z':
        lower_case += 1
print(upper_case)
print(lower_case)

input_string = input("Enter a string: ")
char_count = {}
for char in input_string:
    if char in char_count:
        char_count[char] += 1
    else:
        char_count[char] = 1
for char, count in char_count.items():
    print(char_count)

n = int(input("enter the positive integer(n>0):"))
total_num = 0
for i in range (1, n+1):
  total_num +=i/(i+1)
  print(total_num)

def factorial(n):
    if n == 0:
        return 1
    value = 1
    for i in range(1, n + 1):
        value *= i
    return value
number = int(input("number: "))
print(factorial(number))

net_amount = 0
transaction_log = input("Enter the transaction log (e.g., 'D 100 W 200'): ").split()
for i in range(0, len(transaction_log), 2):
    transaction_type = transaction_log[i]
    amount = int(transaction_log[i + 1])
    if transaction_type == 'D':
        net_amount += amount
    elif transaction_type == 'W':
        net_amount -= amount
print(net_amount)

numbers = input("Enter a sequence of comma-separated numbers: ").split(',')
squared_odds = [str(int(x)**2) for x in numbers if int(x) % 2 != 0]
print(squared_odds)